version: '3.8'
services:

  web:
    build:
      context: ./
      target: candidates
    volumes:
      - .:/src
    command: npm run dev
    ports:
      - "3001:3001"
    depends_on:
     - db
    environment:
      - PORT=${PORT}
      - POSTGRESPORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - USER=${DB_USER}
      - PASSWORD=${DB_PASS}
    networks:
      - cb

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - cb
volumes:
  db:
    driver: local

networks:
  cb:
    driver: bridge
